/**
 * Project Management System
 * 
 * Each project generated by the factory has:
 * - Its own category/domain scorecard
 * - Development progress tracking
 * - Self-similar dashboard structure
 */

import { Category, categories } from './categories';

// Project lifecycle stages
export type ProjectStatus = 'draft' | 'active' | 'paused' | 'completed' | 'archived';

// Source of project creation
export type ProjectSource = 'conceptualize' | 'structured' | 'youtube' | 'rapid' | 'imported';

// Domain scores (same structure as categories but project-specific)
export interface DomainScores {
  demand: number;      // 1-10: Market demand
  effort: number;      // 1-10: Implementation effort
  monetization: number; // 1-10: Revenue potential
  differentiation: number; // 1-10: Competitive advantage
  risk: number;        // 1-10: Risk level
}

// Individual domain within a project
export interface ProjectDomain {
  slug: string;
  name: string;
  description: string;
  scores: DomainScores;
  features: string[];
  status: 'planned' | 'in-progress' | 'completed';
  progress: number; // 0-100
}

// Crew member assignment to a project
export interface CrewAssignment {
  crewMemberId: string;
  role: string;
  assignedAt: string;
  contributions: string[];
}

// Monetization strategy for a project
export interface MonetizationPlan {
  model: string; // 'saas' | 'consulting' | 'marketplace' | 'freemium' | 'enterprise'
  targetPrice: string;
  revenueStreams: string[];
  timeline: string;
}

// Tech stack for a project
export interface TechStack {
  frontend: string[];
  backend: string[];
  infrastructure: string[];
  ai: string[];
  other: string[];
}

// Main Project interface
export interface Project {
  id: string;
  name: string;
  tagline: string;
  description: string;
  
  // Creation context
  source: ProjectSource;
  sourceUrl?: string; // For YouTube-derived projects
  createdAt: string;
  updatedAt: string;
  
  // Status and progress
  status: ProjectStatus;
  progress: number; // 0-100 overall completion
  
  // Category/Domain mapping
  primaryCategory: string; // slug from categories
  domains: ProjectDomain[];
  
  // Scorecard (aggregated from domains)
  scores: DomainScores;
  
  // Team
  crew: CrewAssignment[];
  
  // Business
  monetization: MonetizationPlan;
  targetMarket: string[];
  
  // Technical
  techStack: TechStack;
  
  // Features and milestones
  mvpFeatures: string[];
  completedFeatures: string[];
  milestones: ProjectMilestone[];
  
  // Metrics
  successMetrics: string[];
  
  // Notes and context
  notes: string;
  tags: string[];
}

export interface ProjectMilestone {
  id: string;
  title: string;
  description: string;
  targetDate?: string;
  completedAt?: string;
  status: 'pending' | 'in-progress' | 'completed';
}

// Summary view for lists
export interface ProjectSummary {
  id: string;
  name: string;
  tagline: string;
  status: ProjectStatus;
  progress: number;
  primaryCategory: string;
  scores: DomainScores;
  createdAt: string;
  updatedAt: string;
  source: ProjectSource;
}

/**
 * Calculate aggregate scores from project domains
 */
export function calculateProjectScores(domains: ProjectDomain[]): DomainScores {
  if (domains.length === 0) {
    return { demand: 5, effort: 5, monetization: 5, differentiation: 5, risk: 5 };
  }
  
  const avg = (key: keyof DomainScores) => 
    Math.round(domains.reduce((sum, d) => sum + d.scores[key], 0) / domains.length);
  
  return {
    demand: avg('demand'),
    effort: avg('effort'),
    monetization: avg('monetization'),
    differentiation: avg('differentiation'),
    risk: avg('risk'),
  };
}

/**
 * Calculate overall project progress from domains
 */
export function calculateProjectProgress(domains: ProjectDomain[]): number {
  if (domains.length === 0) return 0;
  return Math.round(domains.reduce((sum, d) => sum + d.progress, 0) / domains.length);
}

/**
 * Create a new project with defaults based on category
 */
export function createProject(
  name: string,
  categorySlug: string,
  source: ProjectSource,
  options: Partial<Project> = {}
): Project {
  const category = categories.find(c => c.slug === categorySlug);
  const now = new Date().toISOString();
  
  // Generate default domains from category
  const defaultDomains: ProjectDomain[] = category ? [{
    slug: 'core',
    name: 'Core Functionality',
    description: `Primary ${category.name} implementation`,
    scores: { ...category.scores },
    features: [],
    status: 'planned',
    progress: 0,
  }] : [];
  
  return {
    id: `proj_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    name,
    tagline: options.tagline || `A ${category?.name || 'new'} project`,
    description: options.description || '',
    
    source,
    sourceUrl: options.sourceUrl,
    createdAt: now,
    updatedAt: now,
    
    status: 'draft',
    progress: 0,
    
    primaryCategory: categorySlug,
    domains: options.domains || defaultDomains,
    scores: category?.scores || { demand: 5, effort: 5, monetization: 5, differentiation: 5, risk: 5 },
    
    crew: options.crew || [],
    
    monetization: options.monetization || {
      model: 'saas',
      targetPrice: 'TBD',
      revenueStreams: [],
      timeline: 'TBD',
    },
    targetMarket: options.targetMarket || [],
    
    techStack: options.techStack || {
      frontend: ['Next.js', 'React', 'TypeScript'],
      backend: ['Node.js', 'Next.js API'],
      infrastructure: ['AWS', 'Docker'],
      ai: [],
      other: [],
    },
    
    mvpFeatures: options.mvpFeatures || [],
    completedFeatures: [],
    milestones: options.milestones || [],
    
    successMetrics: options.successMetrics || [],
    notes: options.notes || '',
    tags: options.tags || [],
  };
}

/**
 * Convert full project to summary for lists
 */
export function toProjectSummary(project: Project): ProjectSummary {
  return {
    id: project.id,
    name: project.name,
    tagline: project.tagline,
    status: project.status,
    progress: project.progress,
    primaryCategory: project.primaryCategory,
    scores: project.scores,
    createdAt: project.createdAt,
    updatedAt: project.updatedAt,
    source: project.source,
  };
}

/**
 * Get category details for a project
 */
export function getProjectCategory(project: Project): Category | undefined {
  return categories.find(c => c.slug === project.primaryCategory);
}

/**
 * Score label helpers
 */
export function getScoreLabel(score: number): string {
  if (score >= 8) return 'Excellent';
  if (score >= 6) return 'Good';
  if (score >= 4) return 'Moderate';
  if (score >= 2) return 'Low';
  return 'Minimal';
}

export function getScoreColor(score: number): string {
  if (score >= 8) return '#10b981'; // green
  if (score >= 6) return '#3b82f6'; // blue
  if (score >= 4) return '#f59e0b'; // amber
  if (score >= 2) return '#f97316'; // orange
  return '#ef4444'; // red
}

export function getStatusColor(status: ProjectStatus): string {
  switch (status) {
    case 'active': return '#10b981';
    case 'draft': return '#6b7280';
    case 'paused': return '#f59e0b';
    case 'completed': return '#3b82f6';
    case 'archived': return '#9ca3af';
    default: return '#6b7280';
  }
}

export function getStatusIcon(status: ProjectStatus): string {
  switch (status) {
    case 'active': return '🚀';
    case 'draft': return '📝';
    case 'paused': return '⏸️';
    case 'completed': return '✅';
    case 'archived': return '📦';
    default: return '📄';
  }
}
