import * as vscode from "vscode";
import * as path from "path";
import { promises as fs } from "fs";

/**
 * File System Manager for crew recommendations and plans
 * Enables the Alex AI extension to read/write crew recommendations, plans, and memory files
 */
export class FileSystemManager {
  private workspaceRoot: vscode.Uri | null = null;
  private dataDir: vscode.Uri;
  private crewMembersDir: vscode.Uri;
  private recommendationsDir: vscode.Uri;
  private plansDir: vscode.Uri;

  constructor() {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (workspaceFolders && workspaceFolders.length > 0) {
      this.workspaceRoot = workspaceFolders[0].uri;
    }

    // Set up directory URIs relative to workspace
    const baseUri = this.workspaceRoot || vscode.Uri.file(process.cwd());
    this.dataDir = vscode.Uri.joinPath(baseUri, "data");
    this.crewMembersDir = vscode.Uri.joinPath(baseUri, "crew-members");
    this.recommendationsDir = vscode.Uri.joinPath(
      this.dataDir,
      "recommendations"
    );
    this.plansDir = vscode.Uri.joinPath(this.dataDir, "plans");
  }

  /**
   * Initialize required directories
   */
  async initialize(): Promise<void> {
    try {
      await this.ensureDirectoryExists(this.dataDir);
      await this.ensureDirectoryExists(this.crewMembersDir);
      await this.ensureDirectoryExists(this.recommendationsDir);
      await this.ensureDirectoryExists(this.plansDir);
      console.log("✅ File System Manager initialized successfully");
    } catch (error) {
      console.error("❌ Failed to initialize FileSystemManager:", error);
      throw error;
    }
  }

  /**
   * Ensure a directory exists, create it if it doesn't
   */
  private async ensureDirectoryExists(dirUri: vscode.Uri): Promise<void> {
    try {
      await vscode.workspace.fs.stat(dirUri);
    } catch {
      // Directory doesn't exist, create it
      await vscode.workspace.fs.createDirectory(dirUri);
    }
  }

  /**
   * Save a crew recommendation to file
   * Format: data/recommendations/[crew-member]-[timestamp].json
   */
  async saveRecommendation(
    crewMember: string,
    recommendation: {
      title: string;
      content: string;
      context?: string;
      action?: string;
      priority?: "high" | "medium" | "low";
      file?: string;
      lineStart?: number;
      lineEnd?: number;
    }
  ): Promise<string> {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const filename = `${crewMember}-recommendation-${timestamp}.json`;
      const fileUri = vscode.Uri.joinPath(this.recommendationsDir, filename);

      const data = {
        id: `rec_${timestamp}`,
        crewMember,
        timestamp: new Date().toISOString(),
        ...recommendation,
      };

      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(JSON.stringify(data, null, 2))
      );

      console.log(
        `💾 Recommendation saved: ${filename} (${crewMember}) - ${recommendation.title}`
      );
      return filename;
    } catch (error) {
      throw new Error(
        `Failed to save recommendation: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Save a plan generated by crew coordination
   * Format: data/plans/[plan-name]-[timestamp].json
   */
  async savePlan(plan: {
    name: string;
    description: string;
    objectives: string[];
    steps: Array<{
      step: number;
      task: string;
      assignedTo?: string;
      priority?: "high" | "medium" | "low";
    }>;
    estimatedTime?: string;
    files?: string[];
    metadata?: Record<string, any>;
  }): Promise<string> {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const filename = `${plan.name}-${timestamp}.json`;
      const fileUri = vscode.Uri.joinPath(this.plansDir, filename);

      const data = {
        id: `plan_${timestamp}`,
        timestamp: new Date().toISOString(),
        ...plan,
      };

      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(JSON.stringify(data, null, 2))
      );

      console.log(`📋 Plan saved: ${filename} - ${plan.name}`);
      return filename;
    } catch (error) {
      throw new Error(
        `Failed to save plan: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Read a crew member's profile
   */
  async loadCrewProfile(crewMember: string): Promise<Record<string, any>> {
    try {
      const filename = `${crewMember}.json`;
      const fileUri = vscode.Uri.joinPath(this.crewMembersDir, filename);
      const content = await vscode.workspace.fs.readFile(fileUri);
      return JSON.parse(content.toString());
    } catch (error) {
      throw new Error(
        `Failed to load crew profile for ${crewMember}: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * List all recommendations
   */
  async listRecommendations(): Promise<
    Array<{ filename: string; data: Record<string, any> }>
  > {
    try {
      const files = await vscode.workspace.fs.readDirectory(
        this.recommendationsDir
      );
      const recommendations = [];

      for (const [filename] of files) {
        if (filename.endsWith(".json")) {
          try {
            const fileUri = vscode.Uri.joinPath(
              this.recommendationsDir,
              filename
            );
            const content = await vscode.workspace.fs.readFile(fileUri);
            recommendations.push({
              filename,
              data: JSON.parse(content.toString()),
            });
          } catch {
            // Skip files that can't be parsed
          }
        }
      }

      return recommendations.sort(
        (a, b) =>
          new Date(b.data.timestamp).getTime() -
          new Date(a.data.timestamp).getTime()
      );
    } catch (error) {
      if (
        error instanceof vscode.FileSystemError &&
        error.code === "FileNotFound"
      ) {
        return [];
      }
      throw error;
    }
  }

  /**
   * List all plans
   */
  async listPlans(): Promise<
    Array<{ filename: string; data: Record<string, any> }>
  > {
    try {
      const files = await vscode.workspace.fs.readDirectory(this.plansDir);
      const plans = [];

      for (const [filename] of files) {
        if (filename.endsWith(".json")) {
          try {
            const fileUri = vscode.Uri.joinPath(this.plansDir, filename);
            const content = await vscode.workspace.fs.readFile(fileUri);
            plans.push({
              filename,
              data: JSON.parse(content.toString()),
            });
          } catch {
            // Skip files that can't be parsed
          }
        }
      }

      return plans.sort(
        (a, b) =>
          new Date(b.data.timestamp).getTime() -
          new Date(a.data.timestamp).getTime()
      );
    } catch (error) {
      if (
        error instanceof vscode.FileSystemError &&
        error.code === "FileNotFound"
      ) {
        return [];
      }
      throw error;
    }
  }

  /**
   * Get recent recommendations (last N items)
   */
  async getRecentRecommendations(
    limit: number = 5
  ): Promise<Array<{ filename: string; data: Record<string, any> }>> {
    const all = await this.listRecommendations();
    return all.slice(0, limit);
  }

  /**
   * Get recent plans (last N items)
   */
  async getRecentPlans(
    limit: number = 5
  ): Promise<Array<{ filename: string; data: Record<string, any> }>> {
    const all = await this.listPlans();
    return all.slice(0, limit);
  }

  /**
   * Read a specific file from the workspace
   */
  async readFile(filePath: string): Promise<string> {
    try {
      const fileUri = vscode.Uri.joinPath(
        this.workspaceRoot || vscode.Uri.file(process.cwd()),
        filePath
      );
      const content = await vscode.workspace.fs.readFile(fileUri);
      return content.toString();
    } catch (error) {
      throw new Error(
        `Failed to read file ${filePath}: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Write to a file in the workspace
   */
  async writeFile(filePath: string, content: string): Promise<void> {
    try {
      const fileUri = vscode.Uri.joinPath(
        this.workspaceRoot || vscode.Uri.file(process.cwd()),
        filePath
      );

      // Ensure parent directory exists
      const parentPath = path.dirname(filePath);
      const parentDir = vscode.Uri.joinPath(
        this.workspaceRoot || vscode.Uri.file(process.cwd()),
        parentPath
      );
      await this.ensureDirectoryExists(parentDir);

      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(content, "utf-8")
      );
      console.log(`✏️ File written: ${filePath}`);
    } catch (error) {
      throw new Error(
        `Failed to write file ${filePath}: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Execute a recommendation by applying a code change
   */
  async executeCodeRecommendation(
    file: string,
    oldCode: string,
    newCode: string
  ): Promise<boolean> {
    try {
      const content = await this.readFile(file);

      if (!content.includes(oldCode)) {
        vscode.window.showWarningMessage(
          "Could not find the code to replace in " + file
        );
        return false;
      }

      const updated = content.replace(oldCode, newCode);
      await this.writeFile(file, updated);

      vscode.window.showInformationMessage(`✅ Applied change to ${file}`);
      return true;
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      vscode.window.showErrorMessage(
        `Failed to execute recommendation: ${message}`
      );
      return false;
    }
  }

  /**
   * Save crew observations/memories to shared data file
   */
  async updateCrewMemories(memories: Record<string, any>): Promise<void> {
    try {
      const fileUri = vscode.Uri.joinPath(this.dataDir, "crew_memories.json");
      const data = {
        timestamp: new Date().toISOString(),
        memories,
      };
      await vscode.workspace.fs.writeFile(
        fileUri,
        Buffer.from(JSON.stringify(data, null, 2))
      );
      console.log("💭 Crew memories updated");
    } catch (error) {
      throw new Error(
        `Failed to update crew memories: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Load crew memories from shared data file
   */
  async loadCrewMemories(): Promise<Record<string, any>> {
    try {
      const fileUri = vscode.Uri.joinPath(this.dataDir, "crew_memories.json");
      const content = await vscode.workspace.fs.readFile(fileUri);
      const data = JSON.parse(content.toString());
      return data.memories || {};
    } catch (error) {
      // File may not exist yet
      return {};
    }
  }

  /**
   * Get workspace root URI
   */
  getWorkspaceRoot(): vscode.Uri | null {
    return this.workspaceRoot;
  }

  /**
   * Get data directory URI
   */
  getDataDir(): vscode.Uri {
    return this.dataDir;
  }

  /**
   * Get recommendations directory URI
   */
  getRecommendationsDir(): vscode.Uri {
    return this.recommendationsDir;
  }

  /**
   * Get plans directory URI
   */
  getPlansDir(): vscode.Uri {
    return this.plansDir;
  }
}
