#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

say(){ printf "%b\n" "$*"; }
ok(){ say "✅ $*"; }
warn(){ say "⚠️  $*"; }
err(){ say "❌ $*"; exit 1; }

# Prefer ~/.zshenv for exported env vars (loads for non-interactive shells too).
ZSHRC="${ZSHRC_PATH:-$HOME/.zshenv}"
if [[ ! -f "$ZSHRC" ]]; then
  ZSHRC="$HOME/.zshrc"
fi
[[ -f "$ZSHRC" ]] || err "Could not find ~/.zshenv or ~/.zshrc. Set ZSHRC_PATH=... to override."

VARS=(
  SUPABASE_URL
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_ANON_KEY
  SUPABASE_PROJECT_ID
)

# Portable ISO-ish timestamp (BSD/GNU compatible)
ISO_TS="$(date '+%Y-%m-%dT%H:%M:%S%z')"

extract_from_file() {
  local var="$1"
  local line
  line="$(grep -E "^[[:space:]]*export[[:space:]]+$var=" "$ZSHRC" | tail -n 1 || true)"
  if [[ -z "${line:-}" ]]; then
    line="$(grep -E "^[[:space:]]*$var=" "$ZSHRC" | tail -n 1 || true)"
  fi
  [[ -z "${line:-}" ]] && return 1

  local val="${line#*${var}=}"
  val="${val%$'\r'}"

  # strip surrounding quotes
  if [[ "$val" == \"*\" && "$val" == *\" ]]; then val="${val:1:${#val}-2}"; fi
  if [[ "$val" == \'*\' && "$val" == *\' ]]; then val="${val:1:${#val}-2}"; fi
  printf "%s" "$val"
}

extract_var() {
  local var="$1"
  local val=""
  if val="$(extract_from_file "$var")"; then
    printf "%s" "$val"
    return 0
  fi
  if [[ -n "${!var:-}" ]]; then
    printf "%s" "${!var}"
    return 0
  fi
  return 1
}

mkdir -p .secrets
OUT=".secrets/.env.local"
STAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP=".secrets/.env.local.bak.${STAMP}"
[[ -f "$OUT" ]] && cp "$OUT" "$BACKUP" && ok "Backed up $OUT -> $BACKUP"

missing=0
{
  echo "# Auto-generated by scripts/secrets/sync_supabase_from_zshrc.sh"
  echo "# Source file: $ZSHRC"
  echo "# $ISO_TS"
  echo
  for var in "${VARS[@]}"; do
    if val="$(extract_var "$var")"; then
      if [[ -z "$val" ]]; then
        warn "$var found but empty"
      else
        esc="${val//\"/\\\"}"
        echo "$var=\"$esc\""
      fi
    else
      warn "$var not found in $ZSHRC and not exported in current shell"
      missing=1
    fi
  done
} > "$OUT"

ok "Wrote $OUT"

if [[ "${MIRROR_TO_ROOT_ENV_LOCAL:-1}" == "1" ]]; then
  cp "$OUT" ".env.local"
  ok "Mirrored .env.local from .secrets/.env.local"
fi

if [[ "$missing" == "1" ]]; then
  say ""
  warn "One or more SUPABASE_* vars were missing."
  say "Fix by adding exports to $ZSHRC (recommended: ~/.zshenv), e.g.:"
  say "  export SUPABASE_URL=\"https://...supabase.co\""
  say "  export SUPABASE_SERVICE_ROLE_KEY=\"...\""
  say "  export SUPABASE_ANON_KEY=\"...\""
  say ""
  say "Then open a NEW terminal (or: source $ZSHRC) and re-run this script."
fi

say ""
say "Verify (no commas):"
say "  grep -n 'SUPABASE_URL' .env.local || true"
say "  node -e 'console.log("SUPABASE_URL:", process.env.SUPABASE_URL); console.log("SRK:", (process.env.SUPABASE_SERVICE_ROLE_KEY||"").slice(0,6))'"
