#!/bin/bash

# This script syncs secrets from a source file to a .env.local file.

set -e # Exit immediately if a command exits with a non-zero status.

# --- Configuration ---
OUT_DIR=".secrets"
mkdir -p "$OUT_DIR"

# Define the list of allowed environment variable keys.
ALLOWLIST=(
    "GH_TOKEN"
    "SUPABASE_URL"
    "SUPABASE_SERVICE_ROLE_KEY"
    "OPENAI_API_KEY"
    "OPENAI_EMBED_MODEL"
    "N8N_WEBHOOK_URL"
    "N8N_PROJECT_WEBHOOK_URL"
    "AWS_REGION"
    "AWS_ACCOUNT_ID"
    "ECR_REPO"
    "AWS_ROLE_TO_ASSUME"
    "EC2_HOST"
    "EC2_USER"
)

# Use ~/.zshrc as the source of truth if it exists.
ENV_SOURCE_FILE="$HOME/.zshrc"
ENV_DUMP="$OUT_DIR/_env_dump.txt"

# --- Main Logic ---

# Check if the source file exists.
if [ ! -f "$ENV_SOURCE_FILE" ]; then
    echo "⚠️ Source secrets file not found: $ENV_SOURCE_FILE"
    exit 1
fi

echo "📖 Reading secrets from $ENV_SOURCE_FILE"

# Create a clean environment dump file.
# We source the file in a subshell to avoid polluting the current shell's environment.
# The subshell will also handle any interactive prompts in the source file.
(
    # Source the file to execute its commands, including any potential interactive prompts.
    # This makes the environment variables available to the 'env' command.
    # Note: This assumes that any interactive prompts can be handled by the user
    # running this script, or that they have default behaviors that do not
    # block script execution.
    source "$ENV_SOURCE_FILE"
    
    # Dump the environment into a file.
    env > "$ENV_DUMP"
)

# Prepare the .env.local file.
ENV_LOCAL_FILE="$OUT_DIR/.env.local"
echo "# Auto-generated by scripts/secrets/sync_from_zshrc.sh" > "$ENV_LOCAL_FILE"
echo "# Do not edit this file directly." >> "$ENV_LOCAL_FILE"
echo "" >> "$ENV_LOCAL_FILE"

# Process the dumped environment variables.
for key in "${ALLOWLIST[@]}"; do
    # Use grep and sed to find the variable and extract its value.
    # This is safer than sourcing directly into the main script's environment.
    VALUE_LINE=$(grep "^$key=" "$ENV_DUMP" || true) # aok if grep fails
    
    if [ -n "$VALUE_LINE" ]; then
        # The value is everything after the first '='.
        VALUE=$(echo "$VALUE_LINE" | sed -n 's/^[^=]*=//p')
        
        # Write the key-value pair to the .env.local file.
        # We need to be careful with values that contain special characters.
        # Enclosing in double quotes is a good practice.
        echo "$key=\"$VALUE\"" >> "$ENV_LOCAL_FILE"
    else
        echo "   -> ⚠️  Warning: Variable '$key' not found in $ENV_SOURCE_FILE or its sourced files."
    fi
done

# Clean up the temporary dump file.
rm "$ENV_DUMP"

echo "✅ Secrets synced to $ENV_LOCAL_FILE"
echo "   -> Remember to run 'cp .secrets/.env.local .env.local' to apply the changes."